### ISSUE TITLE
TypeError: 'zip' object does not support item assignment

### ISSUE THREAD

**Issue by learningneo** [akanimax/natural-language-summary-generation-from-structured-data#4]
Hi buddy,
First - great work! I am trying to set the whole thing up and am facing issues while running the training. I am using Python 3.6 and TF 1.4. I ran both fast_data_preprocessor_partX.py successfully (with a little change in 2, where I had to use encoding while unpickling). I guess the next step would be to run trainer_with_copy_net.py. While running it, I am facing below error:
```
Traceback (most recent call last):
  File "TensorFlow_implementation/trainer_with_copy_net.py", line 83, in <module>
    X, Y = synch_random_shuffle_non_np(zip(field_encodings, content_encodings), label_encodings)
  File "/data/indbks/a619646/projects/natural-language-summary-generation-from-structured-data/TensorFlow_implementation/Summary_Generator/Tensorflow_Graph/utils.py", line 63, in synch_random_shuffle_non_np
    X[:], Y[:] = zip(*combined)
TypeError: 'zip' object does not support item assignment
```
Do let me know if I am doing things in correct order and how to resolve this. Thanks!

**Comment by learningneo** [comment]
For now, I have changed the code to look like `X, Y = zip(*combined)` and removed the `debug` input parameter to avoid error but it failed with runtime error:
```
2018-03-20 11:42:49.932167: W tensorflow/core/framework/op_kernel.cc:1192] Resource exhausted: OOM when allocating tensor with shape[164985,5837]
Traceback (most recent call last):
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[164985,5837]
         [[Node: Trainer/gradients/Training_computations/Decoder/rnn/while/embedding_lookup_1/Enter_grad/concat_2 = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Trainer/gradients/Training_computations/Decoder/rnn/while/embedding_lookup_1/Enter_grad/Switch_1:1, Trainer/gradients/Training_computations/Decoder/rnn/while/embedding_lookup_1_grad/Reshape, Trainer/gradients/Training_computations/Decoder/rnn/while/embedding_lookup_grad/concat/axis)]]
         [[Node: Trainer/gradients/Sub/_194 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1357_Trainer/gradients/Sub", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopTrainer/gradients/Training_computations/Decoder/rnn/while/TensorArrayStack/TensorArrayGatherV3_grad/TensorArrayScatter/TensorArrayScatterV3/StackPopV2/_39)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "TensorFlow_implementation/trainer_with_copy_net.py", line 119, in <module>
    model.train((train_X_field, train_X_content), train_Y, batch_size, no_of_epochs, checkpoint_factor, model_path, model_name, mem_fraction=gpu_memory_usage_fraction) #, debug=True) --gunjan
  File "/data/indbks/a619646/projects/natural-language-summary-generation-from-structured-data/TensorFlow_implementation/Summary_Generator/Model.py", line 187, in train
    self.lab_sequence_lengths: lab_lengths
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[164985,5837]
         [[Node: Trainer/gradients/Training_computations/Decoder/rnn/while/embedding_lookup_1/Enter_grad/concat_2 = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Trainer/gradients/Training_computations/Decoder/rnn/while/embedding_lookup_1/Enter_grad/Switch_1:1, Trainer/gradients/Training_computations/Decoder/rnn/while/embedding_lookup_1_grad/Reshape, Trainer/gradients/Training_computations/Decoder/rnn/while/embedding_lookup_grad/concat/axis)]]
         [[Node: Trainer/gradients/Sub/_194 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1357_Trainer/gradients/Sub", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopTrainer/gradients/Training_computations/Decoder/rnn/while/TensorArrayStack/TensorArrayGatherV3_grad/TensorArrayScatter/TensorArrayScatterV3/StackPopV2/_39)]]

Caused by op 'Trainer/gradients/Training_computations/Decoder/rnn/while/embedding_lookup_1/Enter_grad/concat_2', defined at:
  File "TensorFlow_implementation/trainer_with_copy_net.py", line 118, in <module>
    model = Model(graph, interface_dict, tf.train.AdamOptimizer(learning_rate), field_dict, content_label_dict)
  File "/data/indbks/a619646/projects/natural-language-summary-generation-from-structured-data/TensorFlow_implementation/Summary_Generator/Model.py", line 103, in __init__
    self.__setup_optimizer()
  File "/data/indbks/a619646/projects/natural-language-summary-generation-from-structured-data/TensorFlow_implementation/Summary_Generator/Model.py", line 32, in __setup_optimizer
    self.train_step = self.optimizer.minimize(self.loss)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 343, in minimize
    grad_loss=grad_loss)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/training/optimizer.py", line 414, in compute_gradients
    colocate_gradients_with_ops=colocate_gradients_with_ops)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in gradients
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 353, in _MaybeCompile
    return grad_fn()  # Exit early
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/gradients_impl.py", line 581, in <lambda>
    grad_scope, op, func_call, lambda: grad_fn(op, *out_grads))
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_grad.py", line 219, in _EnterGrad
    result = grad_ctxt.AddBackpropIndexedSlicesAccumulator(op, grad)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2487, in AddBackpropIndexedSlicesAccumulator
    for xa, xv in zip(switch_acc[:2], [indices, values])
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2487, in <listcomp>
    for xa, xv in zip(switch_acc[:2], [indices, values])
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 1099, in concat
    return gen_array_ops._concat_v2(values=values, axis=axis, name=name)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 706, in _concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

...which was originally created as op 'Training_computations/Decoder/rnn/while/embedding_lookup_1/Enter', defined at:
  File "TensorFlow_implementation/trainer_with_copy_net.py", line 112, in <module>
    rev_content_label_dict = rev_content_label_dict
  File "/path/to/program/order_planner_with_copynet.py", line 495, in get_computation_graph
    decoder_lengths=tf_label_seqs_lengths, w_reuse=None)
  File "/path/to/program/order_planner_with_copynet.py", line 481, in decode
    outputs, _, _ = tf.nn.raw_rnn(decoder_cell, decoder_loop_function)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 1082, in raw_rnn
    swap_memory=swap_memory)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2816, in while_loop
    result = loop_context.BuildLoop(cond, body, loop_vars, shape_invariants)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2640, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2590, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/rnn.py", line 1049, in body
    next_time, next_output, cell_state, loop_state)
  File "/path/to/program/order_planner_with_copynet.py", line 442, in decoder_loop_function
    link_attn = get_link_based_attention_vectors(prev_attention_vectors)
  File "/path/to/program/order_planner_with_copynet.py", line 203, in get_link_based_attention_vectors
    matrix_all_values_from = tf.nn.embedding_lookup(Link_Matrix, tf_field_encodings)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 328, in embedding_lookup
    transform_fn=None)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 150, in _embedding_lookup_and_transform
    result = _clip(_gather(params[0], ids, name=name), ids, max_norm)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/embedding_ops.py", line 54, in _gather
    return array_ops.gather(params, ids, name=name)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py", line 2486, in gather
    params, indices, validate_indices=validate_indices, name=name)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/ops/gen_array_ops.py", line 1834, in gather
    validate_indices=validate_indices, name=name)
  File "/opt/conda/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[164985,5837]
         [[Node: Trainer/gradients/Training_computations/Decoder/rnn/while/embedding_lookup_1/Enter_grad/concat_2 = ConcatV2[N=2, T=DT_FLOAT, Tidx=DT_INT32, _device="/job:localhost/replica:0/task:0/device:GPU:0"](Trainer/gradients/Training_computations/Decoder/rnn/while/embedding_lookup_1/Enter_grad/Switch_1:1, Trainer/gradients/Training_computations/Decoder/rnn/while/embedding_lookup_1_grad/Reshape, Trainer/gradients/Training_computations/Decoder/rnn/while/embedding_lookup_grad/concat/axis)]]
         [[Node: Trainer/gradients/Sub/_194 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_1357_Trainer/gradients/Sub", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"](^_cloopTrainer/gradients/Training_computations/Decoder/rnn/while/TensorArrayStack/TensorArrayGatherV3_grad/TensorArrayScatter/TensorArrayScatterV3/StackPopV2/_39)]]
```

Any hints will help!

**Comment by akanimax** [comment]
Hi mate! Thanks for the compliment. :)
You have solved the zip error correctly. I had actually done that, seems like some branch merge messed it up. 
For the OOM error, I see
` OOM when allocating tensor with shape[164985,5837]`
That is when tensorflow is trying to allocate the Embedding matrix. Do you see the size of the first dimension is 164985. This is the full length of the vocabulary. You shouldn't use all the possible words to create the vocabulary unless, you have a huge setup. Where we were training, had three P100 and one P5000 on a single rack. However, while I wanted to train it on my laptop (GTX 1070), I had reduced the vocabulary size to around 20000. There should be a place in the code (The fast_preprocessing files) to set the maximum vocabulary.

Hope this helps.

Also, you might want to reduce the sentence lengths as it might cause problems while training. The lstm backpropagation is again a very memory heavy operation. The tensorflow graph need not be touched anywhere.

**Comment by learningneo** [comment]
Hi there, 
Thanks for the response. I tried reducing the vocab size further to 10K by changing `max_word_length` to 10K in line 42 of fast_processing2 and even after that, the same OOM error came with the same tensor size - which possibly means changing max_word_length is not having any effect on the above. Any further thoughts? You mentioned about reducing sentence lengths, can you indicate where to look at for experimenting with the same?

**Comment by akanimax** [comment]
HI @learningneo, I apologize for missing your above comment, your problem might have been solved by now. Nevertheless, in order to reduce the sequence lengths, you can edit this code -> [https://github.com/akanimax/natural-language-summary-generation-from-structured-data/blob/master/TensorFlow_implementation/fast_data_preprocessor_part1.py#L64](https://github.com/akanimax/natural-language-summary-generation-from-structured-data/blob/master/TensorFlow_implementation/fast_data_preprocessor_part1.py#L64). Instead of grouping all the labels together, you could copy the input pairs for those sentences.

**Comment by shashwath94** [comment]
Hey @akanimax ,
When you say copy the input pairs for the sentences, is it like
<field_names, content_words, label_words[i]> until label length for each subset?

**Comment by akanimax** [comment]
Hi @shashwath94,

This is indeed a sequence length issue and not vocabulary size issue. You can truncate the summary label lengths' to a small size such as 100 or 200. One of the data samples has a summary of length `~1000`. This is what is causing the OOM error. I'll try to add this truncating functionality to the code, but if you do, feel free to open PR.

Thanks!
@akanimax

**Comment by shashwath94** [comment]
Hey @akanimax ,
I'm starting to doubt it is related to the summary length. I tried copying the input pairs of the sentences and also truncating the length to 100 tokens. It starts training and after ~100 steps in epoch 1, the same OOM error shows up.
